### ISSUE TITLE
3D Rotation Todo List

### ISSUE THREAD

**Issue by sjrothfuss** [sjrothfuss/torch-rotate-image#6]
Not an issue, just a place to track and discuss development of 3d rotation.

To Do:

- [ ] Look into 3d rotation matrices ([possible starting point](https://math.libretexts.org/Bookshelves/Applied_Mathematics/Mathematics_for_Game_Developers_(Burzynski)/04%3A_Matrices/4.06%3A_Rotation_Matrices_in_3-Dimensions))
- [ ] Write test for 3d rotation
- [ ] Create module for 3d rotation
- [ ] Draft function to accomplish rotation

**Comment by alisterburt** [comment]
some ideas:

- API for rotations should be `rotation_matrices: np.ndarray` (n, 3, 3)
- you will need to invert both the columns and rows if you want to operate on zyx coordinates c.f. https://github.com/teamtomo/torch-fourier-slice/blob/6abf032f43a2ca0727f6bc3645c4ca8ef5326469/src/torch_fourier_slice/slice_extraction/_extract_central_slices_rfft_3d.py#L38-L48
